# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # runs-on: ${{matrix.os}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # Below codes are from GitHub Marketplace supported Docker Hub 
    - name: Build and Push Docker Image
      # Below is the action with version
      uses: mr-smithers-excellent/docker-build-push@v6    
      with:
        # image: docker-hub-repo/image-name
        # change above image-name into the docker hub repository related name from: docker push new-repo:tagname
        image: jp0908/responsive_portfolio 
        registry: docker.io
        # Below 'secrets' is placeholder
        # Create credentials in 'Settings', the user name is the one before '/', here is jp0908
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      
